import uuid
import datetime
from sqlalchemy import Column, String, JSON, ForeignKey, DateTime, Date, Text
from app.core.database import Base
from app.models.base import TimestampMixin


class WeeklyCareerReport(Base, TimestampMixin):
    """
    Persisted weekly career report. Generated by comparing current state
    vs. the ReadinessSnapshot from ~7 days ago. Reports only actual changes.
    """
    __tablename__ = "weekly_career_reports"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    week_start_date = Column(Date, nullable=False, index=True)
    week_end_date = Column(Date, nullable=False)

    # Score deltas (positive = improved, negative = declined)
    overall_score_delta = Column(String, default="0", nullable=False)
    skill_score_delta = Column(String, default="0", nullable=False)
    resume_score_delta = Column(String, default="0", nullable=False)
    interview_score_delta = Column(String, default="0", nullable=False)
    roadmap_delta = Column(String, default="0", nullable=False)

    # Activity counts during the week (from DB evidence)
    tasks_completed = Column(String, default="0", nullable=False)
    interviews_completed = Column(String, default="0", nullable=False)
    applications_submitted = Column(String, default="0", nullable=False)
    skills_verified = Column(String, default="0", nullable=False)

    # Qualitative fields (derived deterministically, not invented)
    improvements = Column(JSON, default=list, nullable=False)      # ["ATS score up by 5pts", ...]
    achievements_earned = Column(JSON, default=list, nullable=False)
    biggest_weakness = Column(String, nullable=True)
    recommended_focus = Column(String, nullable=True)

    # Optional AI narrative (1-sentence summary)
    ai_narrative = Column(Text, nullable=True)

    generated_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
