"""Update resumes table for structured ATS and target match storage

Revision ID: 7e990e260957
Revises: 859a61590be7
Create Date: 2026-08-18 20:50:52.797231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e990e260957'
down_revision: Union[str, Sequence[str], None] = '859a61590be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('formatting_score', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('keyword_score', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('skills_score', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('experience_score', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('readability_score', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('target_career_name', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('target_match_percentage', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('matching_skills', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('missing_skills', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('ats_breakdown_json', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('parsed_contact_info', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('parsed_education', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('parsed_projects', sa.JSON(), nullable=False))
    op.add_column('resumes', sa.Column('improvement_suggestions', sa.JSON(), nullable=False))
    op.drop_column('resumes', 'target_coverage_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('target_coverage_score', sa.INTEGER(), nullable=False))
    op.drop_column('resumes', 'improvement_suggestions')
    op.drop_column('resumes', 'parsed_projects')
    op.drop_column('resumes', 'parsed_education')
    op.drop_column('resumes', 'parsed_contact_info')
    op.drop_column('resumes', 'ats_breakdown_json')
    op.drop_column('resumes', 'missing_skills')
    op.drop_column('resumes', 'matching_skills')
    op.drop_column('resumes', 'target_match_percentage')
    op.drop_column('resumes', 'target_career_name')
    op.drop_column('resumes', 'readability_score')
    op.drop_column('resumes', 'experience_score')
    op.drop_column('resumes', 'skills_score')
    op.drop_column('resumes', 'keyword_score')
    op.drop_column('resumes', 'formatting_score')
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
