"""Add career catalog and assessment questions tables

Revision ID: 859a61590be7
Revises: da349cf443c8
Create Date: 2026-08-18 20:40:53.643880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859a61590be7'
down_revision: Union[str, Sequence[str], None] = 'da349cf443c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_strengths', sa.JSON(), nullable=False),
    sa.Column('interest_areas', sa.JSON(), nullable=False),
    sa.Column('work_style', sa.String(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('learning_areas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roles_slug'), 'career_roles', ['slug'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_dimension'), 'questions', ['dimension'], unique=False)
    op.add_column('assessment_responses', sa.Column('status', sa.String(), nullable=False))
    op.add_column('assessment_responses', sa.Column('current_step', sa.Integer(), nullable=False))
    op.add_column('assessment_responses', sa.Column('ai_analysis_json', sa.JSON(), nullable=True))
    op.add_column('assessment_responses', sa.Column('selected_target_career', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_responses', 'selected_target_career')
    op.drop_column('assessment_responses', 'ai_analysis_json')
    op.drop_column('assessment_responses', 'current_step')
    op.drop_column('assessment_responses', 'status')
    op.drop_index(op.f('ix_questions_dimension'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_career_roles_slug'), table_name='career_roles')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
