"""Add skill definitions and skill evidence models

Revision ID: b16bae963666
Revises: 7e990e260957
Create Date: 2026-08-18 21:10:01.386234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16bae963666'
down_revision: Union[str, Sequence[str], None] = '7e990e260957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_normalized_name'), ['normalized_name'], unique=False)
        batch_op.drop_column('gap_priority')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gap_priority', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_skills_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
