'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useLanguage } from '@/context/LanguageContext';
import {
  Compass,
  Sparkles,
  FileText,
  Award,
  MapPin,
  Dumbbell,
  Mic,
  Briefcase,
  GraduationCap,
  MessageSquare,
  Settings,
  ArrowRight,
  CheckCircle2,
  HelpCircle,
  Zap,
  Target,
  Clock,
  Layers,
  ChevronRight,
  TrendingUp,
  BrainCircuit,
  BookOpen
} from 'lucide-react';

interface GuideStep {
  step: number;
  id: string;
  titleEn: string;
  titleHi: string;
  categoryEn: string;
  categoryHi: string;
  icon: any;
  route: string;
  durationEn: string;
  durationHi: string;
  descEn: string;
  descHi: string;
  actionPointsEn: string[];
  actionPointsHi: string[];
  whyItMattersEn: string;
  whyItMattersHi: string;
  ctaTextEn: string;
  ctaTextHi: string;
  accentColor: string;
}

const GUIDE_STEPS: GuideStep[] = [
  {
    step: 1,
    id: 'settings',
    titleEn: 'Configure API Key & Language',
    titleHi: 'API कुंजी और भाषा सेट करें',
    categoryEn: 'Setup & Configuration',
    categoryHi: 'सेटअप और कॉन्फ़िगरेशन',
    icon: Settings,
    route: '/settings',
    durationEn: '1 Min',
    durationHi: '1 मिनट',
    descEn: 'Connect your free Groq or Google Gemini API key to activate AI Career features, and select your preferred language (English or Hindi).',
    descHi: 'एआई सुविधाओं को सक्रिय करने के लिए अपनी मुफ़्त Groq या Gemini API Key जोड़ें और अपनी पसंदीदा भाषा (English या हिंदी) चुनें।',
    actionPointsEn: [
      'Enter your API Key in Settings > AI tab for unlimited coaching',
      'Choose Hindi or English for seamless full-platform localization',
      'Toggle theme (Dark/Midnight) according to your comfort'
    ],
    actionPointsHi: [
      'असीमित कोचिंग के लिए Settings > AI टैब में अपनी API Key दर्ज करें',
      'पूरी वेबसाइट के लिए हिंदी या अंग्रेज़ी भाषा का चयन करें',
      'अपनी सुविधा के अनुसार डार्क/मिडनाइट थीम चुनें'
    ],
    whyItMattersEn: 'Enables intelligent AI analysis, personalized mock interviews, and real-time chat coaching.',
    whyItMattersHi: 'यह व्यक्तिगत AI विश्लेषण, मॉक इंटरव्यू और रियल-टाइम चैट कोचिंग को सक्षम बनाता है।',
    ctaTextEn: 'Go to Settings',
    ctaTextHi: 'सेटिंग्स पर जाएं',
    accentColor: 'from-blue-600 to-indigo-600'
  },
  {
    step: 2,
    id: 'assessment',
    titleEn: 'Career Discovery Assessment',
    titleHi: 'करियर खोज मूल्यांकन (असेसमेंट)',
    categoryEn: 'Discovery Phase',
    categoryHi: 'खोज चरण',
    icon: Compass,
    route: '/assessment',
    durationEn: '5-8 Mins',
    durationHi: '5-8 मिनट',
    descEn: 'Take the adaptive AI discovery assessment to uncover your natural technical instincts, cognitive strengths, and ideal career match.',
    descHi: 'अपनी स्वाभाविक ताकत, तकनीकी रुझान और आदर्श करियर मैच जानने के लिए एडाप्टिव AI डिस्कवरी असेसमेंट पूरा करें।',
    actionPointsEn: [
      'Answer 8 easy, practical multiple-choice scenario questions',
      'Each next question is dynamically generated by AI based on your previous answers',
      'Receive your Career Archetype & Gemini AI match recommendations'
    ],
    actionPointsHi: [
      '8 आसान और व्यावहारिक परिदृश्य-आधारित प्रश्नों के उत्तर दें',
      'हर अगला प्रश्न आपके पिछले उत्तर के आधार पर AI द्वारा तैयार किया जाता है',
      'अपना करियर आर्किटाइप और AI अनुशंसित करियर मैच प्राप्त करें'
    ],
    whyItMattersEn: 'Eliminates confusion and establishes clear evidence-based career direction.',
    whyItMattersHi: 'यह करियर के भ्रम को दूर करता है और आपको सही दिशा में आगे बढ़ने का स्पष्ट मार्ग देता है।',
    ctaTextEn: 'Start Assessment',
    ctaTextHi: 'असेसमेंट शुरू करें',
    accentColor: 'from-indigo-600 to-purple-600'
  },
  {
    step: 3,
    id: 'profile',
    titleEn: 'Digital Twin Profile & Target Role',
    titleHi: 'डिजिटल ट्विन प्रोफ़ाइल और लक्ष्य भूमिका',
    categoryEn: 'Profile Calibration',
    categoryHi: 'प्रोफ़ाइल कैलिब्रेशन',
    icon: Sparkles,
    route: '/profile',
    durationEn: '2 Mins',
    durationHi: '2 मिनट',
    descEn: 'Inspect your Career Digital Twin, lock in your primary Target Role, and monitor your live Career Readiness Score (0-100%).',
    descHi: 'अपने Career Digital Twin की समीक्षा करें, अपना मुख्य लक्ष्य करियर चुनें और लाइव करियर तत्परता स्कोर (0-100%) ट्रैक करें।',
    actionPointsEn: [
      'Lock in your Target Career Role (e.g. Full Stack Developer, Data Scientist)',
      'Track your Verified, Supported, and Target Required Skills',
      'View your dynamic Readiness Score as you complete tasks & interviews'
    ],
    actionPointsHi: [
      'अपनी लक्ष्य भूमिका (जैसे Full Stack Developer, Data Scientist) लॉक करें',
      'सत्यापित और आवश्यक कुशलताओं (Skills) की स्थिति देखें',
      'टास्क और इंटरव्यू पूरे करते हुए अपना तत्परता स्कोर बढ़ते हुए देखें'
    ],
    whyItMattersEn: 'Acts as your single source of truth for hiring benchmarks and skill mastery.',
    whyItMattersHi: 'यह उद्योग मानकों के अनुसार आपकी प्रगति को ट्रैक करने का मुख्य केंद्र है।',
    ctaTextEn: 'View Digital Twin',
    ctaTextHi: 'डिजिटल ट्विन देखें',
    accentColor: 'from-purple-600 to-pink-600'
  },
  {
    step: 4,
    id: 'resume',
    titleEn: 'Resume Upload & ATS Optimization',
    titleHi: 'रेज़्यूमे अपलोड और ATS विश्लेषण',
    categoryEn: 'Evidence & Screening',
    categoryHi: 'साक्ष्य और स्क्रीनिंग',
    icon: FileText,
    route: '/resume',
    durationEn: '3 Mins',
    durationHi: '3 मिनट',
    descEn: 'Upload your resume PDF/DOCX to benchmark against industry ATS algorithms and auto-extract verified skill evidence.',
    descHi: 'उद्योग के ATS मानकों पर जांचने और प्रमाणित स्किल्स निकालने के लिए अपना रेज़्यूमे PDF/DOCX अपलोड करें।',
    actionPointsEn: [
      'Get instant ATS Compatibility Score out of 100%',
      'Detect missing high-impact technical keywords for your target role',
      'Use Google XYZ formula suggestions to rewrite bullet points'
    ],
    actionPointsHi: [
      'तुरंत 100% में से अपना ATS स्कोर प्राप्त करें',
      'अपनी लक्ष्य भूमिका के लिए छूटे हुए ज़रूरी कीवर्ड्स का पता लगाएं',
      'Google XYZ फ़ॉर्मूले के आधार पर बुलेट पॉइंट्स सुधारने के सुझाव प्राप्त करें'
    ],
    whyItMattersEn: 'Ensures your resume passes screening bots and captures recruiter attention.',
    whyItMattersHi: 'यह सुनिश्चित करता है कि आपका रेज़्यूमे रिक्रूटर और ATS स्क्रीनिंग में आसानी से पास हो।',
    ctaTextEn: 'Scan Resume',
    ctaTextHi: 'रेज़्यूमे स्कैन करें',
    accentColor: 'from-emerald-600 to-teal-600'
  },
  {
    step: 5,
    id: 'skills',
    titleEn: 'Skill Matrix & Gap Analysis',
    titleHi: 'स्किल मैट्रिक्स और गैप एनालिसिस',
    categoryEn: 'Skill Intelligence',
    categoryHi: 'कौशल विश्लेषण',
    icon: Award,
    route: '/skills',
    durationEn: '3 Mins',
    durationHi: '3 मिनट',
    descEn: 'Deep-dive into your verified skills versus missing prerequisites required by top hiring tech companies.',
    descHi: 'शीर्ष कंपनियों द्वारा मांगी जाने वाली आवश्यक कुशलताओं और अपनी मौजूदा स्किल्स के बीच का अंतर (Gap) देखें।',
    actionPointsEn: [
      'Compare your skills against role benchmarks',
      'Identify High, Medium, and Low priority skill gaps',
      'Review evidence records backing your verified proficiencies'
    ],
    actionPointsHi: [
      'उद्योग की आवश्यकताओं के साथ अपनी स्किल्स की तुलना करें',
      'उच्च (High) और मध्यम प्राथमिकता वाले स्किल गैप्स को पहचानें',
      'अपनी प्रमाणित कुशलताओं के साक्ष्य रिकॉर्ड्स की समीक्षा करें'
    ],
    whyItMattersEn: 'Clarifies exactly what you need to study next without wasting time on irrelevant topics.',
    whyItMattersHi: 'यह स्पष्ट करता है कि आपको आगे क्या सीखना है, जिससे आपका समय व्यर्थ न हो।',
    ctaTextEn: 'Explore Skill Matrix',
    ctaTextHi: 'स्किल मैट्रिक्स देखें',
    accentColor: 'from-amber-600 to-orange-600'
  },
  {
    step: 6,
    id: 'roadmap',
    titleEn: 'Personalized Roadmap & Daily Tasks',
    titleHi: 'पर्सनलाइज्ड रोडमैप और दैनिक टास्क',
    categoryEn: 'Structured Learning',
    categoryHi: 'संरचित अध्ययन',
    icon: MapPin,
    route: '/roadmap',
    durationEn: 'Daily Habit',
    durationHi: 'दैनिक अभ्यास',
    descEn: 'Generate an AI-driven, phase-by-phase learning journey tailored to your schedule (hours/day) and experience level.',
    descHi: 'अपने समय (घंटे/दिन) और स्तर के अनुसार AI द्वारा तैयार किया गया चरणबद्ध (Phase-by-Phase) लर्निंग रोडमैप पाएं।',
    actionPointsEn: [
      'Set daily time budget (e.g. 1-2 hours) and days/week',
      'Check off tasks in the "Today\'s Focus Widget" daily',
      'Master concept explanations, quizzes, and portfolio projects in each phase'
    ],
    actionPointsHi: [
      'दैनिक समय बजट (1-2 घंटे) और सप्ताह के दिन निर्धारित करें',
      'हर दिन "Today\'s Focus Widget" में दिए गए टास्क पूरे करें',
      'प्रत्येक चरण में कॉन्सेप्ट्स, क्विज़ और पोर्टफोलियो प्रोजेक्ट्स पूरे करें'
    ],
    whyItMattersEn: 'Builds consistent momentum and bridges your skill gaps systematically.',
    whyItMattersHi: 'यह आपकी पढ़ाई में निरंतरता लाता है और योजनाबद्ध तरीके से आपके स्किल गैप्स को भरता है।',
    ctaTextEn: 'Open Roadmap',
    ctaTextHi: 'रोडमैप खोलें',
    accentColor: 'from-cyan-600 to-blue-600'
  },
  {
    step: 7,
    id: 'practice',
    titleEn: 'Micro Practice & Coding Exercises',
    titleHi: 'माइक्रो प्रैक्टिस और कोडिंग अभ्यास',
    categoryEn: 'Hands-on Practice',
    categoryHi: 'व्यावहारिक अभ्यास',
    icon: Dumbbell,
    route: '/practice',
    durationEn: '10-15 Mins',
    durationHi: '10-15 मिनट',
    descEn: 'Solve targeted bite-sized technical questions, system design concepts, and coding puzzles linked to your roadmap.',
    descHi: 'अपने रोडमैप से जुड़े छोटे तकनीकी प्रश्न, सिस्टम डिज़ाइन कॉन्सेप्ट्स और कोडिंग पहेलियाँ हल करें।',
    actionPointsEn: [
      'Practice DSA, Database SQL, APIs, and Frameworks',
      'Instant AI evaluation with step-by-step hints and explanations',
      'Directly increases your verified skill confidence score'
    ],
    actionPointsHi: [
      'DSA, डेटाबेस SQL, APIs और फ़्रेमवर्क पर अभ्यास करें',
      'तुरंत AI मूल्यांकन और स्टेप-बाय-स्टेप संकेत प्राप्त करें',
      'अपने डिजिटल ट्विन के स्किल कॉन्फिडेंस स्कोर को बढ़ाएं'
    ],
    whyItMattersEn: 'Transforms theoretical knowledge into muscle memory for technical interview rounds.',
    whyItMattersHi: 'यह आपके सैद्धांतिक ज्ञान को वास्तविक तकनीकी कोडिंग और समस्या-निवारण कौशल में बदलता है।',
    ctaTextEn: 'Start Practice',
    ctaTextHi: 'अभ्यास शुरू करें',
    accentColor: 'from-rose-600 to-red-600'
  },
  {
    step: 8,
    id: 'interview',
    titleEn: 'AI Mock Interviews & Voice Coaching',
    titleHi: 'AI मॉक इंटरव्यू और मूल्यांकन',
    categoryEn: 'Interview Readiness',
    categoryHi: 'इंटरव्यू की तैयारी',
    icon: Mic,
    route: '/interview',
    durationEn: '15-20 Mins',
    durationHi: '15-20 मिनट',
    descEn: 'Simulate realistic Technical, Behavioral (STAR method), or HR interviews with adaptive AI voice/text evaluation.',
    descHi: 'वास्तविक Technical, Behavioral (STAR पद्धति) या HR इंटरव्यू का AI के साथ अभ्यास करें और विस्तृत फीडबैक पाएं।',
    actionPointsEn: [
      'Choose mode: Technical Deep-Dive, Behavioral STAR, or System Architecture',
      'Answer questions via typing or live microphone voice speech',
      'Receive instant evaluation: score out of 100, STAR breakdown, strengths, and improved answer rewrite'
    ],
    actionPointsHi: [
      'मोड चुनें: Technical, Behavioral STAR, या System Architecture',
      'टाइप करके या माइक्रोफ़ोन से बोलकर अपना उत्तर दें',
      'तुरंत 100 में से स्कोर, STAR विश्लेषण, ताकत और बेहतर उत्तर सुझाव प्राप्त करें'
    ],
    whyItMattersEn: 'Eliminates interview anxiety and sharpens your communication under real pressure.',
    whyItMattersHi: 'यह इंटरव्यू के डर को खत्म करता है और आपके उत्तर देने के आत्मविश्वास को मजबूत करता है।',
    ctaTextEn: 'Start Mock Interview',
    ctaTextHi: 'मॉक इंटरव्यू शुरू करें',
    accentColor: 'from-violet-600 to-indigo-600'
  },
  {
    step: 9,
    id: 'jobs',
    titleEn: 'Job Engine & Pipeline Tracker',
    titleHi: 'जॉब इंजन और एप्लीकेशन ट्रैकर',
    categoryEn: 'Job Search & Tracking',
    categoryHi: 'नौकरी खोज और ट्रैकिंग',
    icon: Briefcase,
    route: '/jobs',
    durationEn: 'Weekly',
    durationHi: 'साप्ताहिक',
    descEn: 'Discover tailored tech job opportunities scored against your Digital Twin profile and manage your hiring pipeline.',
    descHi: 'अपने डिजिटल ट्विन के अनुसार मैच होने वाली नौकरियाँ खोजें और अपनी एप्लीकेशन स्थिति को ट्रैक करें।',
    actionPointsEn: [
      'View Job Match Score % for each opening',
      'Identify exact matching vs missing skills before applying',
      'Track pipeline stages: Saved, Applied, Interviewing, Offered'
    ],
    actionPointsHi: [
      'प्रत्येक जॉब के लिए अपना मैच स्कोर (% Match) देखें',
      'अप्लाई करने से पहले आवश्यक कुशलताओं की जांच करें',
      'एप्लीकेशन स्टेटस (Applied, Interviewing, Offered) एक जगह मैनेज करें'
    ],
    whyItMattersEn: 'Allows you to apply only to high-conversion roles where you stand out.',
    whyItMattersHi: 'यह आपको केवल उन्हीं नौकरियों में आवेदन करने में मदद करता है जहाँ आपके चयन की संभावना सबसे अधिक हो।',
    ctaTextEn: 'Explore Jobs',
    ctaTextHi: 'नौकरियां देखें',
    accentColor: 'from-teal-600 to-emerald-600'
  },
  {
    step: 10,
    id: 'placement',
    titleEn: 'Placement Readiness & 1-Page Career Brief',
    titleHi: 'प्लेसमेंट तैयारी और 1-Page करियर ब्रीफ़',
    categoryEn: 'Final Milestone',
    categoryHi: 'अंतिम मील का पत्थर',
    icon: GraduationCap,
    route: '/placement',
    durationEn: 'Milestone',
    durationHi: 'अंतिम चरण',
    descEn: 'Validate the 10-Point Placement Checklist and generate your official 1-Page Student Career Brief for campus hiring drives.',
    descHi: '10-पॉइंट प्लेसमेंट चेकलिस्ट की पुष्टि करें और कैंपस प्लेसमेंट के लिए अपना आधिकारिक 1-Page Student Career Brief डाउनलोड करें।',
    actionPointsEn: [
      'Complete the 10-point verified readiness checklist',
      'Export the recruiter-ready 1-Page Student Career Brief with verified metrics',
      'Present tangible proof of ATS score, interview readiness, and skill mastery'
    ],
    actionPointsHi: [
      '10-बिंदु प्लेसमेंट तत्परता चेकलिस्ट पूरी करें',
      'सत्यापित मेट्रिक्स के साथ रिक्रूटर-रेडी 1-Page Student Career Brief डाउनलोड करें',
      'रिक्रूटर्स और कॉलेज प्लेसमेंट सेल को अपनी संपूर्ण तैयारी का साक्ष्य प्रस्तुत करें'
    ],
    whyItMattersEn: 'Gives recruiters instant confidence in your verified hiring readiness.',
    whyItMattersHi: 'यह रिक्रूटर्स को आपकी वास्तविक तैयारी पर तुरंत भरोसा दिलाता है।',
    ctaTextEn: 'View Placement Brief',
    ctaTextHi: 'प्लेसमेंट ब्रीफ़ देखें',
    accentColor: 'from-amber-600 to-yellow-600'
  }
];

export default function GuidePage() {
  const { language } = useLanguage();
  const isHi = language === 'hi';
  const [activeFilter, setActiveFilter] = useState<'all' | 'phase1' | 'phase2' | 'phase3' | 'phase4'>('all');

  const filteredSteps = GUIDE_STEPS.filter((step) => {
    if (activeFilter === 'phase1') return step.step <= 3;
    if (activeFilter === 'phase2') return step.step >= 4 && step.step <= 6;
    if (activeFilter === 'phase3') return step.step >= 7 && step.step <= 8;
    if (activeFilter === 'phase4') return step.step >= 9;
    return true;
  });

  return (
    <div className="max-w-6xl mx-auto space-y-10 pb-16">
      {/* Hero Header Banner */}
      <div className="p-8 md:p-10 rounded-3xl bg-gradient-to-r from-indigo-950/80 via-slate-900 to-purple-950/80 border border-indigo-500/20 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 space-y-4">
          <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 text-xs font-bold uppercase tracking-wider">
            <BookOpen className="w-4 h-4 text-indigo-400" />
            <span>{isHi ? 'संपूर्ण प्लेटफॉर्म मास्टर गाइड' : 'Complete Platform Master Guide'}</span>
          </div>

          <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
            {isHi 
              ? 'AI Career Coach का प्रभावी उपयोग कैसे करें (User Journey)' 
              : 'How to Effectively Use AI Career Coach (Step-by-Step Flow)'}
          </h1>

          <p className="text-slate-300 text-sm md:text-base max-w-3xl leading-relaxed">
            {isHi
              ? 'यह संरचित 10-चरणीय कार्यप्रवाह आपको अपनी प्रतिभा पहचानने, रेज़्यूमे ऑप्टिमाइज़ करने, स्किल्स में महारत हासिल करने और AI मॉक इंटरव्यू से टॉप जॉब पाने तक का सीधा मार्ग दिखाता है।'
              : 'This structured 10-step master workflow guides you from discovering your natural strengths and optimizing your resume to mastering technical skills and cracking top interviews.'}
          </p>

          {/* Quick Metrics */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-slate-800/80">
            <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-slate-800">
              <span className="text-xs font-semibold text-slate-400">{isHi ? 'कुल चरण' : 'Total Stages'}</span>
              <p className="text-xl font-bold text-indigo-400">10 Steps</p>
            </div>
            <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-slate-800">
              <span className="text-xs font-semibold text-slate-400">{isHi ? 'शुरुआती समय' : 'Initial Setup'}</span>
              <p className="text-xl font-bold text-emerald-400">10-15 Mins</p>
            </div>
            <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-slate-800">
              <span className="text-xs font-semibold text-slate-400">{isHi ? 'भाषा समर्थन' : 'Languages'}</span>
              <p className="text-xl font-bold text-purple-400">English & हिंदी</p>
            </div>
            <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-slate-800">
              <span className="text-xs font-semibold text-slate-400">{isHi ? 'अंतिम परिणाम' : 'Final Outcome'}</span>
              <p className="text-xl font-bold text-amber-400">{isHi ? 'जॉब रेडी ब्रीफ़' : '1-Page Brief'}</p>
            </div>
          </div>
        </div>
      </div>

      {/* 24/7 AI Coach Floating Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-emerald-950/50 via-slate-900 to-indigo-950/50 border border-emerald-500/30 flex flex-col md:flex-row items-center justify-between gap-5 shadow-lg">
        <div className="flex items-center space-x-4">
          <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shrink-0">
            <MessageSquare className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">
              {isHi ? '💡 किसी भी कदम पर मदद चाहिए? 24/7 AI करियर कोच से बात करें' : '💡 Need help at any step? Chat with your 24/7 AI Career Coach'}
            </h3>
            <p className="text-xs text-slate-300 mt-0.5">
              {isHi 
                ? 'रेज़्यूमे सलाह, कोडिंग प्रश्न या इंटरव्यू रणनीति के लिए सीधे AI कोच से हिंदी या अंग्रेजी में पूछें।'
                : 'Ask questions about your career direction, resume bullets, or coding problems anytime in English or Hindi.'}
            </p>
          </div>
        </div>
        <Link
          href="/chat"
          className="px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs flex items-center space-x-2 shrink-0 transition-all shadow-md shadow-emerald-600/30"
        >
          <span>{isHi ? 'AI कोच से बात करें' : 'Open AI Coach Chat'}</span>
          <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

      {/* Phase Filters */}
      <div className="flex items-center space-x-2 overflow-x-auto pb-2 scrollbar-none">
        <button
          onClick={() => setActiveFilter('all')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            activeFilter === 'all'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'bg-slate-900 text-slate-400 hover:bg-slate-800 border border-slate-800'
          }`}
        >
          {isHi ? 'सभी चरण (10)' : 'All Steps (10)'}
        </button>
        <button
          onClick={() => setActiveFilter('phase1')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            activeFilter === 'phase1'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'bg-slate-900 text-slate-400 hover:bg-slate-800 border border-slate-800'
          }`}
        >
          {isHi ? 'चरण 1: खोज और सेटअप (1-3)' : 'Phase 1: Discovery & Setup (1-3)'}
        </button>
        <button
          onClick={() => setActiveFilter('phase2')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            activeFilter === 'phase2'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'bg-slate-900 text-slate-400 hover:bg-slate-800 border border-slate-800'
          }`}
        >
          {isHi ? 'चरण 2: रेज़्यूमे और स्किल्स (4-6)' : 'Phase 2: Resume & Skills (4-6)'}
        </button>
        <button
          onClick={() => setActiveFilter('phase3')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            activeFilter === 'phase3'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'bg-slate-900 text-slate-400 hover:bg-slate-800 border border-slate-800'
          }`}
        >
          {isHi ? 'चरण 3: अभ्यास और इंटरव्यू (7-8)' : 'Phase 3: Practice & Interviews (7-8)'}
        </button>
        <button
          onClick={() => setActiveFilter('phase4')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all shrink-0 ${
            activeFilter === 'phase4'
              ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
              : 'bg-slate-900 text-slate-400 hover:bg-slate-800 border border-slate-800'
          }`}
        >
          {isHi ? 'चरण 4: जॉब्स और प्लेसमेंट (9-10)' : 'Phase 4: Jobs & Placement (9-10)'}
        </button>
      </div>

      {/* Step by Step Flow Cards */}
      <div className="space-y-6">
        {filteredSteps.map((step) => {
          const IconComp = step.icon;
          return (
            <div
              key={step.id}
              className="p-6 md:p-8 rounded-3xl bg-slate-900/70 border border-slate-800 hover:border-slate-700 transition-all space-y-6 shadow-xl relative group"
            >
              {/* Card Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="flex items-center space-x-4">
                  <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${step.accentColor} flex items-center justify-center text-white font-black text-lg shadow-lg shrink-0`}>
                    {step.step}
                  </div>
                  <div>
                    <div className="flex items-center space-x-2">
                      <span className="text-[11px] font-bold text-indigo-400 uppercase tracking-wider">
                        {isHi ? step.categoryHi : step.categoryEn}
                      </span>
                      <span className="text-slate-600">•</span>
                      <span className="text-[11px] font-semibold text-slate-400 flex items-center space-x-1">
                        <Clock className="w-3 h-3 text-slate-400" />
                        <span>{isHi ? step.durationHi : step.durationEn}</span>
                      </span>
                    </div>
                    <h2 className="text-xl md:text-2xl font-bold text-white">
                      {isHi ? step.titleHi : step.titleEn}
                    </h2>
                  </div>
                </div>

                <Link
                  href={step.route}
                  className="px-5 py-2.5 rounded-xl bg-slate-800 hover:bg-indigo-600 text-white font-semibold text-xs flex items-center space-x-2 self-start sm:self-auto transition-all border border-slate-700 hover:border-indigo-500 shadow-md group-hover:scale-105"
                >
                  <span>{isHi ? step.ctaTextHi : step.ctaTextEn}</span>
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>

              {/* Description */}
              <p className="text-sm text-slate-300 leading-relaxed">
                {isHi ? step.descHi : step.descEn}
              </p>

              {/* Action Points Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {(isHi ? step.actionPointsHi : step.actionPointsEn).map((point, pIdx) => (
                  <div
                    key={pIdx}
                    className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800/80 flex items-start space-x-3 text-xs text-slate-300"
                  >
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                    <span className="leading-relaxed">{point}</span>
                  </div>
                ))}
              </div>

              {/* Why it Matters Footer */}
              <div className="p-3.5 rounded-xl bg-indigo-950/30 border border-indigo-500/20 flex items-start space-x-2.5 text-xs text-indigo-300">
                <Sparkles className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
                <div>
                  <strong className="text-white font-semibold">
                    {isHi ? 'यह क्यों महत्वपूर्ण है: ' : 'Why It Matters: '}
                  </strong>
                  <span>{isHi ? step.whyItMattersHi : step.whyItMattersEn}</span>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Final Call to Action Box */}
      <div className="p-8 rounded-3xl bg-gradient-to-r from-indigo-900/60 via-purple-900/50 to-slate-900 border border-indigo-500/30 text-center space-y-4 shadow-2xl">
        <h2 className="text-2xl font-bold text-white">
          {isHi ? 'अपनी करियर यात्रा शुरू करने के लिए तैयार हैं?' : 'Ready to Start Your Career Journey?'}
        </h2>
        <p className="text-slate-300 text-xs md:text-sm max-w-xl mx-auto">
          {isHi 
            ? 'पहला कदम उठाएं: डिस्कवरी असेसमेंट पूरा करें और अपनी पसंदीदा लक्ष्य भूमिका चुनें!' 
            : 'Take the first step now: complete your Discovery Assessment to unlock your tailored roadmap!'}
        </p>
        <div className="pt-2 flex items-center justify-center space-x-4">
          <Link
            href="/assessment"
            className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-sm flex items-center space-x-2 transition-all shadow-lg shadow-indigo-600/30"
          >
            <span>{isHi ? 'असेसमेंट शुरू करें →' : 'Start Assessment →'}</span>
          </Link>
          <Link
            href="/dashboard"
            className="px-6 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 font-semibold text-sm transition-all"
          >
            <span>{isHi ? 'डैशबोर्ड पर जाएं' : 'Go to Dashboard'}</span>
          </Link>
        </div>
      </div>
    </div>
  );
}
